import { createSlice } from '@reduxjs/toolkit';

// Define the address slice using createSlice from Redux Toolkit
export const addressSlice = createSlice({
    name: 'address',  // Name of the slice
    initialState: {
        // Initial state structure for the address slice
        address: {
            countryLive: "",       // Country where the user currently lives
            addressLineOne: "",    // First line of the address
            addressLineTwo: "",    // Second line of the address (optional)
            city: "",              // City of the address
            district: "",          // District or region of the address
            phoneNumber: "",       // Contact phone number
            postalCode: "",        // Postal or ZIP code
        },
    },
    reducers: {
        // Reducer to set the countryLive state
        setCountryLive: (state, action) => {
            state.address.countryLive = action.payload;
        },
        // Reducer to set the first line of the address
        setAddressLineOne: (state, action) => {
            state.address.addressLineOne = action.payload;
        },
        // Reducer to set the second line of the address
        setAddressLineTwo: (state, action) => {
            state.address.addressLineTwo = action.payload;
        },
        // Reducer to set the city
        setCity: (state, action) => {
            state.address.city = action.payload;
        },
        // Reducer to set the district or region
        setDistrict: (state, action) => {
            state.address.district = action.payload;
        },
        // Reducer to set the phone number
        setPhoneNumber: (state, action) => {
            state.address.phoneNumber = action.payload;
        },
        // Reducer to set the postal code
        setPostalCode: (state, action) => {
            state.address.postalCode = action.payload;
        },
    },
});

// Export the actions generated by createSlice for each reducer
export const {
    setCountryLive,
    setAddressLineOne,
    setAddressLineTwo,
    setCity,
    setDistrict,
    setPhoneNumber,
    setPostalCode
} = addressSlice.actions;

// Export the reducer to be included in the Redux store
export default addressSlice.reducer;
