// Importing the createSlice function from Redux Toolkit
import { createSlice } from '@reduxjs/toolkit';

// Defining the personalDetails slice with an initial state and reducers
export const personalDetails = createSlice({
    name: 'personalDetails', // Name of the slice
    initialState: {
        primaryApplicant: {
            firstName: "",          // First name of the primary applicant
            lastName: "",           // Last name of the primary applicant
            middleName: "",         // Middle name of the primary applicant (if applicable)
            dateOfBirth: "",        // Date of birth of the primary applicant
            sex: "",                // Gender/sex of the primary applicant
            countryBorn: "",        // Country of birth of the primary applicant
            countryEligibility: "", // Country of eligibility for immigration
            cityBorn: "",           // City of birth of the primary applicant
            photograph: "",         // Photograph of the primary applicant
            email: "",              // Email of the primary applicant
        },
    },
    reducers: {
        // Reducer for setting the first name
        setFirstName: (state, action) => {
            state.primaryApplicant.firstName = action.payload;
        },
        // Reducer for setting the last name
        setLastName: (state, action) => {
            state.primaryApplicant.lastName = action.payload;
        },
        // Reducer for setting the middle name
        setMiddleName: (state, action) => {
            state.primaryApplicant.middleName = action.payload;
        },
        // Reducer for setting the date of birth
        setDateOfBirth: (state, action) => {
            state.primaryApplicant.dateOfBirth = action.payload;
        },
        // Reducer for setting the sex/gender
        setSex: (state, action) => {
            state.primaryApplicant.sex = action.payload;
        },
        // Reducer for setting the country of birth
        setCountryBorn: (state, action) => {
            state.primaryApplicant.countryBorn = action.payload;
        },
        // Reducer for setting the country of eligibility for immigration
        setCountryEligibility: (state, action) => {
            state.primaryApplicant.countryEligibility = action.payload;
        },
        // Reducer for setting the city of birth
        setCityBorn: (state, action) => {
            state.primaryApplicant.cityBorn = action.payload;
        },
        // Reducer for setting the photograph
        setPhotograph: (state, action) => {
            state.primaryApplicant.photograph = action.payload;
        },
        // Reducer for setting the email address of the primary applicant
        setEmailPrimaryApplicant: (state, action) => {
            state.primaryApplicant.email = action.payload;
        },
    },
});

// Exporting the action creators generated by createSlice
export const {
    setFirstName,
    setLastName,
    setMiddleName,
    setDateOfBirth,
    setSex,
    setCountryBorn,
    setCountryEligibility,
    setCityBorn,
    setPhotograph,
    setEmailPrimaryApplicant,
} = personalDetails.actions;

// Exporting the reducer to be included in the Redux store
export default personalDetails.reducer;
